----- 10/29/22 15:05:10 -----
Traceback (most recent call last):
  File "/Users/maxhorowitz/dev/chess/simple-chess-game/gui.py", line 174, in play_as
    game = make_AI_move(game, color)
  File "/Users/maxhorowitz/dev/chess/simple-chess-game/gui.py", line 148, in make_AI_move
    new_game = chess.make_move(game, chess.get_AI_move(game, AI_SEARCH_DEPTH))
  File "/Users/maxhorowitz/dev/chess/simple-chess-game/chess.py", line 1340, in get_AI_move
    if find_in_book(game):
  File "/Users/maxhorowitz/dev/chess/simple-chess-game/chess.py", line 1426, in find_in_book
    book_file = open("book.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'book.txt'

Playing as WHITE:
	f2f4
	rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
	rnbqkbnr/pppppppp/8/8/5P2/8/PPPPP1PP/RNBQKBNR b KQkq f3 0 1
-----------------------------

